// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/bigquery/storage/v1/stream.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_google_2fcloud_2fbigquery_2fstorage_2fv1_2fstream_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_google_2fcloud_2fbigquery_2fstorage_2fv1_2fstream_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3013000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3013000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "google/api/field_behavior.pb.h"
#include "google/api/resource.pb.h"
#include "google/cloud/bigquery/storage/v1/arrow.pb.h"
#include "google/cloud/bigquery/storage/v1/avro.pb.h"
#include <google/protobuf/timestamp.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_google_2fcloud_2fbigquery_2fstorage_2fv1_2fstream_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_google_2fcloud_2fbigquery_2fstorage_2fv1_2fstream_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_google_2fcloud_2fbigquery_2fstorage_2fv1_2fstream_2eproto;
namespace google {
namespace cloud {
namespace bigquery {
namespace storage {
namespace v1 {
class ReadSession;
class ReadSessionDefaultTypeInternal;
extern ReadSessionDefaultTypeInternal _ReadSession_default_instance_;
class ReadSession_TableModifiers;
class ReadSession_TableModifiersDefaultTypeInternal;
extern ReadSession_TableModifiersDefaultTypeInternal _ReadSession_TableModifiers_default_instance_;
class ReadSession_TableReadOptions;
class ReadSession_TableReadOptionsDefaultTypeInternal;
extern ReadSession_TableReadOptionsDefaultTypeInternal _ReadSession_TableReadOptions_default_instance_;
class ReadStream;
class ReadStreamDefaultTypeInternal;
extern ReadStreamDefaultTypeInternal _ReadStream_default_instance_;
}  // namespace v1
}  // namespace storage
}  // namespace bigquery
}  // namespace cloud
}  // namespace google
PROTOBUF_NAMESPACE_OPEN
template<> ::google::cloud::bigquery::storage::v1::ReadSession* Arena::CreateMaybeMessage<::google::cloud::bigquery::storage::v1::ReadSession>(Arena*);
template<> ::google::cloud::bigquery::storage::v1::ReadSession_TableModifiers* Arena::CreateMaybeMessage<::google::cloud::bigquery::storage::v1::ReadSession_TableModifiers>(Arena*);
template<> ::google::cloud::bigquery::storage::v1::ReadSession_TableReadOptions* Arena::CreateMaybeMessage<::google::cloud::bigquery::storage::v1::ReadSession_TableReadOptions>(Arena*);
template<> ::google::cloud::bigquery::storage::v1::ReadStream* Arena::CreateMaybeMessage<::google::cloud::bigquery::storage::v1::ReadStream>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace google {
namespace cloud {
namespace bigquery {
namespace storage {
namespace v1 {

enum DataFormat : int {
  DATA_FORMAT_UNSPECIFIED = 0,
  AVRO = 1,
  ARROW = 2,
  DataFormat_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  DataFormat_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool DataFormat_IsValid(int value);
constexpr DataFormat DataFormat_MIN = DATA_FORMAT_UNSPECIFIED;
constexpr DataFormat DataFormat_MAX = ARROW;
constexpr int DataFormat_ARRAYSIZE = DataFormat_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DataFormat_descriptor();
template<typename T>
inline const std::string& DataFormat_Name(T enum_t_value) {
  static_assert(::std::is_same<T, DataFormat>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function DataFormat_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    DataFormat_descriptor(), enum_t_value);
}
inline bool DataFormat_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, DataFormat* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<DataFormat>(
    DataFormat_descriptor(), name, value);
}
// ===================================================================

class ReadSession_TableModifiers PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:google.cloud.bigquery.storage.v1.ReadSession.TableModifiers) */ {
 public:
  inline ReadSession_TableModifiers() : ReadSession_TableModifiers(nullptr) {}
  virtual ~ReadSession_TableModifiers();

  ReadSession_TableModifiers(const ReadSession_TableModifiers& from);
  ReadSession_TableModifiers(ReadSession_TableModifiers&& from) noexcept
    : ReadSession_TableModifiers() {
    *this = ::std::move(from);
  }

  inline ReadSession_TableModifiers& operator=(const ReadSession_TableModifiers& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReadSession_TableModifiers& operator=(ReadSession_TableModifiers&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ReadSession_TableModifiers& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReadSession_TableModifiers* internal_default_instance() {
    return reinterpret_cast<const ReadSession_TableModifiers*>(
               &_ReadSession_TableModifiers_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ReadSession_TableModifiers& a, ReadSession_TableModifiers& b) {
    a.Swap(&b);
  }
  inline void Swap(ReadSession_TableModifiers* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReadSession_TableModifiers* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ReadSession_TableModifiers* New() const final {
    return CreateMaybeMessage<ReadSession_TableModifiers>(nullptr);
  }

  ReadSession_TableModifiers* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ReadSession_TableModifiers>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ReadSession_TableModifiers& from);
  void MergeFrom(const ReadSession_TableModifiers& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReadSession_TableModifiers* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "google.cloud.bigquery.storage.v1.ReadSession.TableModifiers";
  }
  protected:
  explicit ReadSession_TableModifiers(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_google_2fcloud_2fbigquery_2fstorage_2fv1_2fstream_2eproto);
    return ::descriptor_table_google_2fcloud_2fbigquery_2fstorage_2fv1_2fstream_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSnapshotTimeFieldNumber = 1,
  };
  // .google.protobuf.Timestamp snapshot_time = 1;
  bool has_snapshot_time() const;
  private:
  bool _internal_has_snapshot_time() const;
  public:
  void clear_snapshot_time();
  const PROTOBUF_NAMESPACE_ID::Timestamp& snapshot_time() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* release_snapshot_time();
  PROTOBUF_NAMESPACE_ID::Timestamp* mutable_snapshot_time();
  void set_allocated_snapshot_time(PROTOBUF_NAMESPACE_ID::Timestamp* snapshot_time);
  private:
  const PROTOBUF_NAMESPACE_ID::Timestamp& _internal_snapshot_time() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_snapshot_time();
  public:
  void unsafe_arena_set_allocated_snapshot_time(
      PROTOBUF_NAMESPACE_ID::Timestamp* snapshot_time);
  PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_snapshot_time();

  // @@protoc_insertion_point(class_scope:google.cloud.bigquery.storage.v1.ReadSession.TableModifiers)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  PROTOBUF_NAMESPACE_ID::Timestamp* snapshot_time_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_google_2fcloud_2fbigquery_2fstorage_2fv1_2fstream_2eproto;
};
// -------------------------------------------------------------------

class ReadSession_TableReadOptions PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:google.cloud.bigquery.storage.v1.ReadSession.TableReadOptions) */ {
 public:
  inline ReadSession_TableReadOptions() : ReadSession_TableReadOptions(nullptr) {}
  virtual ~ReadSession_TableReadOptions();

  ReadSession_TableReadOptions(const ReadSession_TableReadOptions& from);
  ReadSession_TableReadOptions(ReadSession_TableReadOptions&& from) noexcept
    : ReadSession_TableReadOptions() {
    *this = ::std::move(from);
  }

  inline ReadSession_TableReadOptions& operator=(const ReadSession_TableReadOptions& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReadSession_TableReadOptions& operator=(ReadSession_TableReadOptions&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ReadSession_TableReadOptions& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReadSession_TableReadOptions* internal_default_instance() {
    return reinterpret_cast<const ReadSession_TableReadOptions*>(
               &_ReadSession_TableReadOptions_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ReadSession_TableReadOptions& a, ReadSession_TableReadOptions& b) {
    a.Swap(&b);
  }
  inline void Swap(ReadSession_TableReadOptions* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReadSession_TableReadOptions* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ReadSession_TableReadOptions* New() const final {
    return CreateMaybeMessage<ReadSession_TableReadOptions>(nullptr);
  }

  ReadSession_TableReadOptions* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ReadSession_TableReadOptions>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ReadSession_TableReadOptions& from);
  void MergeFrom(const ReadSession_TableReadOptions& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReadSession_TableReadOptions* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "google.cloud.bigquery.storage.v1.ReadSession.TableReadOptions";
  }
  protected:
  explicit ReadSession_TableReadOptions(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_google_2fcloud_2fbigquery_2fstorage_2fv1_2fstream_2eproto);
    return ::descriptor_table_google_2fcloud_2fbigquery_2fstorage_2fv1_2fstream_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSelectedFieldsFieldNumber = 1,
    kRowRestrictionFieldNumber = 2,
  };
  // repeated string selected_fields = 1;
  int selected_fields_size() const;
  private:
  int _internal_selected_fields_size() const;
  public:
  void clear_selected_fields();
  const std::string& selected_fields(int index) const;
  std::string* mutable_selected_fields(int index);
  void set_selected_fields(int index, const std::string& value);
  void set_selected_fields(int index, std::string&& value);
  void set_selected_fields(int index, const char* value);
  void set_selected_fields(int index, const char* value, size_t size);
  std::string* add_selected_fields();
  void add_selected_fields(const std::string& value);
  void add_selected_fields(std::string&& value);
  void add_selected_fields(const char* value);
  void add_selected_fields(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& selected_fields() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_selected_fields();
  private:
  const std::string& _internal_selected_fields(int index) const;
  std::string* _internal_add_selected_fields();
  public:

  // string row_restriction = 2;
  void clear_row_restriction();
  const std::string& row_restriction() const;
  void set_row_restriction(const std::string& value);
  void set_row_restriction(std::string&& value);
  void set_row_restriction(const char* value);
  void set_row_restriction(const char* value, size_t size);
  std::string* mutable_row_restriction();
  std::string* release_row_restriction();
  void set_allocated_row_restriction(std::string* row_restriction);
  private:
  const std::string& _internal_row_restriction() const;
  void _internal_set_row_restriction(const std::string& value);
  std::string* _internal_mutable_row_restriction();
  public:

  // @@protoc_insertion_point(class_scope:google.cloud.bigquery.storage.v1.ReadSession.TableReadOptions)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> selected_fields_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr row_restriction_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_google_2fcloud_2fbigquery_2fstorage_2fv1_2fstream_2eproto;
};
// -------------------------------------------------------------------

class ReadSession PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:google.cloud.bigquery.storage.v1.ReadSession) */ {
 public:
  inline ReadSession() : ReadSession(nullptr) {}
  virtual ~ReadSession();

  ReadSession(const ReadSession& from);
  ReadSession(ReadSession&& from) noexcept
    : ReadSession() {
    *this = ::std::move(from);
  }

  inline ReadSession& operator=(const ReadSession& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReadSession& operator=(ReadSession&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ReadSession& default_instance();

  enum SchemaCase {
    kAvroSchema = 4,
    kArrowSchema = 5,
    SCHEMA_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReadSession* internal_default_instance() {
    return reinterpret_cast<const ReadSession*>(
               &_ReadSession_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ReadSession& a, ReadSession& b) {
    a.Swap(&b);
  }
  inline void Swap(ReadSession* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReadSession* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ReadSession* New() const final {
    return CreateMaybeMessage<ReadSession>(nullptr);
  }

  ReadSession* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ReadSession>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ReadSession& from);
  void MergeFrom(const ReadSession& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReadSession* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "google.cloud.bigquery.storage.v1.ReadSession";
  }
  protected:
  explicit ReadSession(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_google_2fcloud_2fbigquery_2fstorage_2fv1_2fstream_2eproto);
    return ::descriptor_table_google_2fcloud_2fbigquery_2fstorage_2fv1_2fstream_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef ReadSession_TableModifiers TableModifiers;
  typedef ReadSession_TableReadOptions TableReadOptions;

  // accessors -------------------------------------------------------

  enum : int {
    kStreamsFieldNumber = 10,
    kNameFieldNumber = 1,
    kTableFieldNumber = 6,
    kExpireTimeFieldNumber = 2,
    kTableModifiersFieldNumber = 7,
    kReadOptionsFieldNumber = 8,
    kDataFormatFieldNumber = 3,
    kAvroSchemaFieldNumber = 4,
    kArrowSchemaFieldNumber = 5,
  };
  // repeated .google.cloud.bigquery.storage.v1.ReadStream streams = 10 [(.google.api.field_behavior) = OUTPUT_ONLY];
  int streams_size() const;
  private:
  int _internal_streams_size() const;
  public:
  void clear_streams();
  ::google::cloud::bigquery::storage::v1::ReadStream* mutable_streams(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::google::cloud::bigquery::storage::v1::ReadStream >*
      mutable_streams();
  private:
  const ::google::cloud::bigquery::storage::v1::ReadStream& _internal_streams(int index) const;
  ::google::cloud::bigquery::storage::v1::ReadStream* _internal_add_streams();
  public:
  const ::google::cloud::bigquery::storage::v1::ReadStream& streams(int index) const;
  ::google::cloud::bigquery::storage::v1::ReadStream* add_streams();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::google::cloud::bigquery::storage::v1::ReadStream >&
      streams() const;

  // string name = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string table = 6 [(.google.api.field_behavior) = IMMUTABLE, (.google.api.resource_reference) = {
  void clear_table();
  const std::string& table() const;
  void set_table(const std::string& value);
  void set_table(std::string&& value);
  void set_table(const char* value);
  void set_table(const char* value, size_t size);
  std::string* mutable_table();
  std::string* release_table();
  void set_allocated_table(std::string* table);
  private:
  const std::string& _internal_table() const;
  void _internal_set_table(const std::string& value);
  std::string* _internal_mutable_table();
  public:

  // .google.protobuf.Timestamp expire_time = 2 [(.google.api.field_behavior) = OUTPUT_ONLY];
  bool has_expire_time() const;
  private:
  bool _internal_has_expire_time() const;
  public:
  void clear_expire_time();
  const PROTOBUF_NAMESPACE_ID::Timestamp& expire_time() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* release_expire_time();
  PROTOBUF_NAMESPACE_ID::Timestamp* mutable_expire_time();
  void set_allocated_expire_time(PROTOBUF_NAMESPACE_ID::Timestamp* expire_time);
  private:
  const PROTOBUF_NAMESPACE_ID::Timestamp& _internal_expire_time() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_expire_time();
  public:
  void unsafe_arena_set_allocated_expire_time(
      PROTOBUF_NAMESPACE_ID::Timestamp* expire_time);
  PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_expire_time();

  // .google.cloud.bigquery.storage.v1.ReadSession.TableModifiers table_modifiers = 7 [(.google.api.field_behavior) = OPTIONAL];
  bool has_table_modifiers() const;
  private:
  bool _internal_has_table_modifiers() const;
  public:
  void clear_table_modifiers();
  const ::google::cloud::bigquery::storage::v1::ReadSession_TableModifiers& table_modifiers() const;
  ::google::cloud::bigquery::storage::v1::ReadSession_TableModifiers* release_table_modifiers();
  ::google::cloud::bigquery::storage::v1::ReadSession_TableModifiers* mutable_table_modifiers();
  void set_allocated_table_modifiers(::google::cloud::bigquery::storage::v1::ReadSession_TableModifiers* table_modifiers);
  private:
  const ::google::cloud::bigquery::storage::v1::ReadSession_TableModifiers& _internal_table_modifiers() const;
  ::google::cloud::bigquery::storage::v1::ReadSession_TableModifiers* _internal_mutable_table_modifiers();
  public:
  void unsafe_arena_set_allocated_table_modifiers(
      ::google::cloud::bigquery::storage::v1::ReadSession_TableModifiers* table_modifiers);
  ::google::cloud::bigquery::storage::v1::ReadSession_TableModifiers* unsafe_arena_release_table_modifiers();

  // .google.cloud.bigquery.storage.v1.ReadSession.TableReadOptions read_options = 8 [(.google.api.field_behavior) = OPTIONAL];
  bool has_read_options() const;
  private:
  bool _internal_has_read_options() const;
  public:
  void clear_read_options();
  const ::google::cloud::bigquery::storage::v1::ReadSession_TableReadOptions& read_options() const;
  ::google::cloud::bigquery::storage::v1::ReadSession_TableReadOptions* release_read_options();
  ::google::cloud::bigquery::storage::v1::ReadSession_TableReadOptions* mutable_read_options();
  void set_allocated_read_options(::google::cloud::bigquery::storage::v1::ReadSession_TableReadOptions* read_options);
  private:
  const ::google::cloud::bigquery::storage::v1::ReadSession_TableReadOptions& _internal_read_options() const;
  ::google::cloud::bigquery::storage::v1::ReadSession_TableReadOptions* _internal_mutable_read_options();
  public:
  void unsafe_arena_set_allocated_read_options(
      ::google::cloud::bigquery::storage::v1::ReadSession_TableReadOptions* read_options);
  ::google::cloud::bigquery::storage::v1::ReadSession_TableReadOptions* unsafe_arena_release_read_options();

  // .google.cloud.bigquery.storage.v1.DataFormat data_format = 3 [(.google.api.field_behavior) = IMMUTABLE];
  void clear_data_format();
  ::google::cloud::bigquery::storage::v1::DataFormat data_format() const;
  void set_data_format(::google::cloud::bigquery::storage::v1::DataFormat value);
  private:
  ::google::cloud::bigquery::storage::v1::DataFormat _internal_data_format() const;
  void _internal_set_data_format(::google::cloud::bigquery::storage::v1::DataFormat value);
  public:

  // .google.cloud.bigquery.storage.v1.AvroSchema avro_schema = 4 [(.google.api.field_behavior) = OUTPUT_ONLY];
  bool has_avro_schema() const;
  private:
  bool _internal_has_avro_schema() const;
  public:
  void clear_avro_schema();
  const ::google::cloud::bigquery::storage::v1::AvroSchema& avro_schema() const;
  ::google::cloud::bigquery::storage::v1::AvroSchema* release_avro_schema();
  ::google::cloud::bigquery::storage::v1::AvroSchema* mutable_avro_schema();
  void set_allocated_avro_schema(::google::cloud::bigquery::storage::v1::AvroSchema* avro_schema);
  private:
  const ::google::cloud::bigquery::storage::v1::AvroSchema& _internal_avro_schema() const;
  ::google::cloud::bigquery::storage::v1::AvroSchema* _internal_mutable_avro_schema();
  public:
  void unsafe_arena_set_allocated_avro_schema(
      ::google::cloud::bigquery::storage::v1::AvroSchema* avro_schema);
  ::google::cloud::bigquery::storage::v1::AvroSchema* unsafe_arena_release_avro_schema();

  // .google.cloud.bigquery.storage.v1.ArrowSchema arrow_schema = 5 [(.google.api.field_behavior) = OUTPUT_ONLY];
  bool has_arrow_schema() const;
  private:
  bool _internal_has_arrow_schema() const;
  public:
  void clear_arrow_schema();
  const ::google::cloud::bigquery::storage::v1::ArrowSchema& arrow_schema() const;
  ::google::cloud::bigquery::storage::v1::ArrowSchema* release_arrow_schema();
  ::google::cloud::bigquery::storage::v1::ArrowSchema* mutable_arrow_schema();
  void set_allocated_arrow_schema(::google::cloud::bigquery::storage::v1::ArrowSchema* arrow_schema);
  private:
  const ::google::cloud::bigquery::storage::v1::ArrowSchema& _internal_arrow_schema() const;
  ::google::cloud::bigquery::storage::v1::ArrowSchema* _internal_mutable_arrow_schema();
  public:
  void unsafe_arena_set_allocated_arrow_schema(
      ::google::cloud::bigquery::storage::v1::ArrowSchema* arrow_schema);
  ::google::cloud::bigquery::storage::v1::ArrowSchema* unsafe_arena_release_arrow_schema();

  void clear_schema();
  SchemaCase schema_case() const;
  // @@protoc_insertion_point(class_scope:google.cloud.bigquery.storage.v1.ReadSession)
 private:
  class _Internal;
  void set_has_avro_schema();
  void set_has_arrow_schema();

  inline bool has_schema() const;
  inline void clear_has_schema();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::google::cloud::bigquery::storage::v1::ReadStream > streams_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr table_;
  PROTOBUF_NAMESPACE_ID::Timestamp* expire_time_;
  ::google::cloud::bigquery::storage::v1::ReadSession_TableModifiers* table_modifiers_;
  ::google::cloud::bigquery::storage::v1::ReadSession_TableReadOptions* read_options_;
  int data_format_;
  union SchemaUnion {
    SchemaUnion() {}
    ::google::cloud::bigquery::storage::v1::AvroSchema* avro_schema_;
    ::google::cloud::bigquery::storage::v1::ArrowSchema* arrow_schema_;
  } schema_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _oneof_case_[1];

  friend struct ::TableStruct_google_2fcloud_2fbigquery_2fstorage_2fv1_2fstream_2eproto;
};
// -------------------------------------------------------------------

class ReadStream PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:google.cloud.bigquery.storage.v1.ReadStream) */ {
 public:
  inline ReadStream() : ReadStream(nullptr) {}
  virtual ~ReadStream();

  ReadStream(const ReadStream& from);
  ReadStream(ReadStream&& from) noexcept
    : ReadStream() {
    *this = ::std::move(from);
  }

  inline ReadStream& operator=(const ReadStream& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReadStream& operator=(ReadStream&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ReadStream& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReadStream* internal_default_instance() {
    return reinterpret_cast<const ReadStream*>(
               &_ReadStream_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ReadStream& a, ReadStream& b) {
    a.Swap(&b);
  }
  inline void Swap(ReadStream* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReadStream* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ReadStream* New() const final {
    return CreateMaybeMessage<ReadStream>(nullptr);
  }

  ReadStream* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ReadStream>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ReadStream& from);
  void MergeFrom(const ReadStream& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReadStream* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "google.cloud.bigquery.storage.v1.ReadStream";
  }
  protected:
  explicit ReadStream(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_google_2fcloud_2fbigquery_2fstorage_2fv1_2fstream_2eproto);
    return ::descriptor_table_google_2fcloud_2fbigquery_2fstorage_2fv1_2fstream_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
  };
  // string name = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // @@protoc_insertion_point(class_scope:google.cloud.bigquery.storage.v1.ReadStream)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_google_2fcloud_2fbigquery_2fstorage_2fv1_2fstream_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ReadSession_TableModifiers

// .google.protobuf.Timestamp snapshot_time = 1;
inline bool ReadSession_TableModifiers::_internal_has_snapshot_time() const {
  return this != internal_default_instance() && snapshot_time_ != nullptr;
}
inline bool ReadSession_TableModifiers::has_snapshot_time() const {
  return _internal_has_snapshot_time();
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& ReadSession_TableModifiers::_internal_snapshot_time() const {
  const PROTOBUF_NAMESPACE_ID::Timestamp* p = snapshot_time_;
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Timestamp*>(
      &PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& ReadSession_TableModifiers::snapshot_time() const {
  // @@protoc_insertion_point(field_get:google.cloud.bigquery.storage.v1.ReadSession.TableModifiers.snapshot_time)
  return _internal_snapshot_time();
}
inline void ReadSession_TableModifiers::unsafe_arena_set_allocated_snapshot_time(
    PROTOBUF_NAMESPACE_ID::Timestamp* snapshot_time) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(snapshot_time_);
  }
  snapshot_time_ = snapshot_time;
  if (snapshot_time) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:google.cloud.bigquery.storage.v1.ReadSession.TableModifiers.snapshot_time)
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* ReadSession_TableModifiers::release_snapshot_time() {
  
  PROTOBUF_NAMESPACE_ID::Timestamp* temp = snapshot_time_;
  snapshot_time_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* ReadSession_TableModifiers::unsafe_arena_release_snapshot_time() {
  // @@protoc_insertion_point(field_release:google.cloud.bigquery.storage.v1.ReadSession.TableModifiers.snapshot_time)
  
  PROTOBUF_NAMESPACE_ID::Timestamp* temp = snapshot_time_;
  snapshot_time_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* ReadSession_TableModifiers::_internal_mutable_snapshot_time() {
  
  if (snapshot_time_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Timestamp>(GetArena());
    snapshot_time_ = p;
  }
  return snapshot_time_;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* ReadSession_TableModifiers::mutable_snapshot_time() {
  // @@protoc_insertion_point(field_mutable:google.cloud.bigquery.storage.v1.ReadSession.TableModifiers.snapshot_time)
  return _internal_mutable_snapshot_time();
}
inline void ReadSession_TableModifiers::set_allocated_snapshot_time(PROTOBUF_NAMESPACE_ID::Timestamp* snapshot_time) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(snapshot_time_);
  }
  if (snapshot_time) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(snapshot_time)->GetArena();
    if (message_arena != submessage_arena) {
      snapshot_time = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, snapshot_time, submessage_arena);
    }
    
  } else {
    
  }
  snapshot_time_ = snapshot_time;
  // @@protoc_insertion_point(field_set_allocated:google.cloud.bigquery.storage.v1.ReadSession.TableModifiers.snapshot_time)
}

// -------------------------------------------------------------------

// ReadSession_TableReadOptions

// repeated string selected_fields = 1;
inline int ReadSession_TableReadOptions::_internal_selected_fields_size() const {
  return selected_fields_.size();
}
inline int ReadSession_TableReadOptions::selected_fields_size() const {
  return _internal_selected_fields_size();
}
inline void ReadSession_TableReadOptions::clear_selected_fields() {
  selected_fields_.Clear();
}
inline std::string* ReadSession_TableReadOptions::add_selected_fields() {
  // @@protoc_insertion_point(field_add_mutable:google.cloud.bigquery.storage.v1.ReadSession.TableReadOptions.selected_fields)
  return _internal_add_selected_fields();
}
inline const std::string& ReadSession_TableReadOptions::_internal_selected_fields(int index) const {
  return selected_fields_.Get(index);
}
inline const std::string& ReadSession_TableReadOptions::selected_fields(int index) const {
  // @@protoc_insertion_point(field_get:google.cloud.bigquery.storage.v1.ReadSession.TableReadOptions.selected_fields)
  return _internal_selected_fields(index);
}
inline std::string* ReadSession_TableReadOptions::mutable_selected_fields(int index) {
  // @@protoc_insertion_point(field_mutable:google.cloud.bigquery.storage.v1.ReadSession.TableReadOptions.selected_fields)
  return selected_fields_.Mutable(index);
}
inline void ReadSession_TableReadOptions::set_selected_fields(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:google.cloud.bigquery.storage.v1.ReadSession.TableReadOptions.selected_fields)
  selected_fields_.Mutable(index)->assign(value);
}
inline void ReadSession_TableReadOptions::set_selected_fields(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:google.cloud.bigquery.storage.v1.ReadSession.TableReadOptions.selected_fields)
  selected_fields_.Mutable(index)->assign(std::move(value));
}
inline void ReadSession_TableReadOptions::set_selected_fields(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  selected_fields_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:google.cloud.bigquery.storage.v1.ReadSession.TableReadOptions.selected_fields)
}
inline void ReadSession_TableReadOptions::set_selected_fields(int index, const char* value, size_t size) {
  selected_fields_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:google.cloud.bigquery.storage.v1.ReadSession.TableReadOptions.selected_fields)
}
inline std::string* ReadSession_TableReadOptions::_internal_add_selected_fields() {
  return selected_fields_.Add();
}
inline void ReadSession_TableReadOptions::add_selected_fields(const std::string& value) {
  selected_fields_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:google.cloud.bigquery.storage.v1.ReadSession.TableReadOptions.selected_fields)
}
inline void ReadSession_TableReadOptions::add_selected_fields(std::string&& value) {
  selected_fields_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:google.cloud.bigquery.storage.v1.ReadSession.TableReadOptions.selected_fields)
}
inline void ReadSession_TableReadOptions::add_selected_fields(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  selected_fields_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:google.cloud.bigquery.storage.v1.ReadSession.TableReadOptions.selected_fields)
}
inline void ReadSession_TableReadOptions::add_selected_fields(const char* value, size_t size) {
  selected_fields_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:google.cloud.bigquery.storage.v1.ReadSession.TableReadOptions.selected_fields)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
ReadSession_TableReadOptions::selected_fields() const {
  // @@protoc_insertion_point(field_list:google.cloud.bigquery.storage.v1.ReadSession.TableReadOptions.selected_fields)
  return selected_fields_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
ReadSession_TableReadOptions::mutable_selected_fields() {
  // @@protoc_insertion_point(field_mutable_list:google.cloud.bigquery.storage.v1.ReadSession.TableReadOptions.selected_fields)
  return &selected_fields_;
}

// string row_restriction = 2;
inline void ReadSession_TableReadOptions::clear_row_restriction() {
  row_restriction_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ReadSession_TableReadOptions::row_restriction() const {
  // @@protoc_insertion_point(field_get:google.cloud.bigquery.storage.v1.ReadSession.TableReadOptions.row_restriction)
  return _internal_row_restriction();
}
inline void ReadSession_TableReadOptions::set_row_restriction(const std::string& value) {
  _internal_set_row_restriction(value);
  // @@protoc_insertion_point(field_set:google.cloud.bigquery.storage.v1.ReadSession.TableReadOptions.row_restriction)
}
inline std::string* ReadSession_TableReadOptions::mutable_row_restriction() {
  // @@protoc_insertion_point(field_mutable:google.cloud.bigquery.storage.v1.ReadSession.TableReadOptions.row_restriction)
  return _internal_mutable_row_restriction();
}
inline const std::string& ReadSession_TableReadOptions::_internal_row_restriction() const {
  return row_restriction_.Get();
}
inline void ReadSession_TableReadOptions::_internal_set_row_restriction(const std::string& value) {
  
  row_restriction_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ReadSession_TableReadOptions::set_row_restriction(std::string&& value) {
  
  row_restriction_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:google.cloud.bigquery.storage.v1.ReadSession.TableReadOptions.row_restriction)
}
inline void ReadSession_TableReadOptions::set_row_restriction(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  row_restriction_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:google.cloud.bigquery.storage.v1.ReadSession.TableReadOptions.row_restriction)
}
inline void ReadSession_TableReadOptions::set_row_restriction(const char* value,
    size_t size) {
  
  row_restriction_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:google.cloud.bigquery.storage.v1.ReadSession.TableReadOptions.row_restriction)
}
inline std::string* ReadSession_TableReadOptions::_internal_mutable_row_restriction() {
  
  return row_restriction_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ReadSession_TableReadOptions::release_row_restriction() {
  // @@protoc_insertion_point(field_release:google.cloud.bigquery.storage.v1.ReadSession.TableReadOptions.row_restriction)
  return row_restriction_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ReadSession_TableReadOptions::set_allocated_row_restriction(std::string* row_restriction) {
  if (row_restriction != nullptr) {
    
  } else {
    
  }
  row_restriction_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), row_restriction,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:google.cloud.bigquery.storage.v1.ReadSession.TableReadOptions.row_restriction)
}

// -------------------------------------------------------------------

// ReadSession

// string name = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];
inline void ReadSession::clear_name() {
  name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ReadSession::name() const {
  // @@protoc_insertion_point(field_get:google.cloud.bigquery.storage.v1.ReadSession.name)
  return _internal_name();
}
inline void ReadSession::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:google.cloud.bigquery.storage.v1.ReadSession.name)
}
inline std::string* ReadSession::mutable_name() {
  // @@protoc_insertion_point(field_mutable:google.cloud.bigquery.storage.v1.ReadSession.name)
  return _internal_mutable_name();
}
inline const std::string& ReadSession::_internal_name() const {
  return name_.Get();
}
inline void ReadSession::_internal_set_name(const std::string& value) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ReadSession::set_name(std::string&& value) {
  
  name_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:google.cloud.bigquery.storage.v1.ReadSession.name)
}
inline void ReadSession::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:google.cloud.bigquery.storage.v1.ReadSession.name)
}
inline void ReadSession::set_name(const char* value,
    size_t size) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:google.cloud.bigquery.storage.v1.ReadSession.name)
}
inline std::string* ReadSession::_internal_mutable_name() {
  
  return name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ReadSession::release_name() {
  // @@protoc_insertion_point(field_release:google.cloud.bigquery.storage.v1.ReadSession.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ReadSession::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:google.cloud.bigquery.storage.v1.ReadSession.name)
}

// .google.protobuf.Timestamp expire_time = 2 [(.google.api.field_behavior) = OUTPUT_ONLY];
inline bool ReadSession::_internal_has_expire_time() const {
  return this != internal_default_instance() && expire_time_ != nullptr;
}
inline bool ReadSession::has_expire_time() const {
  return _internal_has_expire_time();
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& ReadSession::_internal_expire_time() const {
  const PROTOBUF_NAMESPACE_ID::Timestamp* p = expire_time_;
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Timestamp*>(
      &PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& ReadSession::expire_time() const {
  // @@protoc_insertion_point(field_get:google.cloud.bigquery.storage.v1.ReadSession.expire_time)
  return _internal_expire_time();
}
inline void ReadSession::unsafe_arena_set_allocated_expire_time(
    PROTOBUF_NAMESPACE_ID::Timestamp* expire_time) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(expire_time_);
  }
  expire_time_ = expire_time;
  if (expire_time) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:google.cloud.bigquery.storage.v1.ReadSession.expire_time)
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* ReadSession::release_expire_time() {
  
  PROTOBUF_NAMESPACE_ID::Timestamp* temp = expire_time_;
  expire_time_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* ReadSession::unsafe_arena_release_expire_time() {
  // @@protoc_insertion_point(field_release:google.cloud.bigquery.storage.v1.ReadSession.expire_time)
  
  PROTOBUF_NAMESPACE_ID::Timestamp* temp = expire_time_;
  expire_time_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* ReadSession::_internal_mutable_expire_time() {
  
  if (expire_time_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Timestamp>(GetArena());
    expire_time_ = p;
  }
  return expire_time_;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* ReadSession::mutable_expire_time() {
  // @@protoc_insertion_point(field_mutable:google.cloud.bigquery.storage.v1.ReadSession.expire_time)
  return _internal_mutable_expire_time();
}
inline void ReadSession::set_allocated_expire_time(PROTOBUF_NAMESPACE_ID::Timestamp* expire_time) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(expire_time_);
  }
  if (expire_time) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(expire_time)->GetArena();
    if (message_arena != submessage_arena) {
      expire_time = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, expire_time, submessage_arena);
    }
    
  } else {
    
  }
  expire_time_ = expire_time;
  // @@protoc_insertion_point(field_set_allocated:google.cloud.bigquery.storage.v1.ReadSession.expire_time)
}

// .google.cloud.bigquery.storage.v1.DataFormat data_format = 3 [(.google.api.field_behavior) = IMMUTABLE];
inline void ReadSession::clear_data_format() {
  data_format_ = 0;
}
inline ::google::cloud::bigquery::storage::v1::DataFormat ReadSession::_internal_data_format() const {
  return static_cast< ::google::cloud::bigquery::storage::v1::DataFormat >(data_format_);
}
inline ::google::cloud::bigquery::storage::v1::DataFormat ReadSession::data_format() const {
  // @@protoc_insertion_point(field_get:google.cloud.bigquery.storage.v1.ReadSession.data_format)
  return _internal_data_format();
}
inline void ReadSession::_internal_set_data_format(::google::cloud::bigquery::storage::v1::DataFormat value) {
  
  data_format_ = value;
}
inline void ReadSession::set_data_format(::google::cloud::bigquery::storage::v1::DataFormat value) {
  _internal_set_data_format(value);
  // @@protoc_insertion_point(field_set:google.cloud.bigquery.storage.v1.ReadSession.data_format)
}

// .google.cloud.bigquery.storage.v1.AvroSchema avro_schema = 4 [(.google.api.field_behavior) = OUTPUT_ONLY];
inline bool ReadSession::_internal_has_avro_schema() const {
  return schema_case() == kAvroSchema;
}
inline bool ReadSession::has_avro_schema() const {
  return _internal_has_avro_schema();
}
inline void ReadSession::set_has_avro_schema() {
  _oneof_case_[0] = kAvroSchema;
}
inline ::google::cloud::bigquery::storage::v1::AvroSchema* ReadSession::release_avro_schema() {
  // @@protoc_insertion_point(field_release:google.cloud.bigquery.storage.v1.ReadSession.avro_schema)
  if (_internal_has_avro_schema()) {
    clear_has_schema();
      ::google::cloud::bigquery::storage::v1::AvroSchema* temp = schema_.avro_schema_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    schema_.avro_schema_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::google::cloud::bigquery::storage::v1::AvroSchema& ReadSession::_internal_avro_schema() const {
  return _internal_has_avro_schema()
      ? *schema_.avro_schema_
      : *reinterpret_cast< ::google::cloud::bigquery::storage::v1::AvroSchema*>(&::google::cloud::bigquery::storage::v1::_AvroSchema_default_instance_);
}
inline const ::google::cloud::bigquery::storage::v1::AvroSchema& ReadSession::avro_schema() const {
  // @@protoc_insertion_point(field_get:google.cloud.bigquery.storage.v1.ReadSession.avro_schema)
  return _internal_avro_schema();
}
inline ::google::cloud::bigquery::storage::v1::AvroSchema* ReadSession::unsafe_arena_release_avro_schema() {
  // @@protoc_insertion_point(field_unsafe_arena_release:google.cloud.bigquery.storage.v1.ReadSession.avro_schema)
  if (_internal_has_avro_schema()) {
    clear_has_schema();
    ::google::cloud::bigquery::storage::v1::AvroSchema* temp = schema_.avro_schema_;
    schema_.avro_schema_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ReadSession::unsafe_arena_set_allocated_avro_schema(::google::cloud::bigquery::storage::v1::AvroSchema* avro_schema) {
  clear_schema();
  if (avro_schema) {
    set_has_avro_schema();
    schema_.avro_schema_ = avro_schema;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:google.cloud.bigquery.storage.v1.ReadSession.avro_schema)
}
inline ::google::cloud::bigquery::storage::v1::AvroSchema* ReadSession::_internal_mutable_avro_schema() {
  if (!_internal_has_avro_schema()) {
    clear_schema();
    set_has_avro_schema();
    schema_.avro_schema_ = CreateMaybeMessage< ::google::cloud::bigquery::storage::v1::AvroSchema >(GetArena());
  }
  return schema_.avro_schema_;
}
inline ::google::cloud::bigquery::storage::v1::AvroSchema* ReadSession::mutable_avro_schema() {
  // @@protoc_insertion_point(field_mutable:google.cloud.bigquery.storage.v1.ReadSession.avro_schema)
  return _internal_mutable_avro_schema();
}

// .google.cloud.bigquery.storage.v1.ArrowSchema arrow_schema = 5 [(.google.api.field_behavior) = OUTPUT_ONLY];
inline bool ReadSession::_internal_has_arrow_schema() const {
  return schema_case() == kArrowSchema;
}
inline bool ReadSession::has_arrow_schema() const {
  return _internal_has_arrow_schema();
}
inline void ReadSession::set_has_arrow_schema() {
  _oneof_case_[0] = kArrowSchema;
}
inline ::google::cloud::bigquery::storage::v1::ArrowSchema* ReadSession::release_arrow_schema() {
  // @@protoc_insertion_point(field_release:google.cloud.bigquery.storage.v1.ReadSession.arrow_schema)
  if (_internal_has_arrow_schema()) {
    clear_has_schema();
      ::google::cloud::bigquery::storage::v1::ArrowSchema* temp = schema_.arrow_schema_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    schema_.arrow_schema_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::google::cloud::bigquery::storage::v1::ArrowSchema& ReadSession::_internal_arrow_schema() const {
  return _internal_has_arrow_schema()
      ? *schema_.arrow_schema_
      : *reinterpret_cast< ::google::cloud::bigquery::storage::v1::ArrowSchema*>(&::google::cloud::bigquery::storage::v1::_ArrowSchema_default_instance_);
}
inline const ::google::cloud::bigquery::storage::v1::ArrowSchema& ReadSession::arrow_schema() const {
  // @@protoc_insertion_point(field_get:google.cloud.bigquery.storage.v1.ReadSession.arrow_schema)
  return _internal_arrow_schema();
}
inline ::google::cloud::bigquery::storage::v1::ArrowSchema* ReadSession::unsafe_arena_release_arrow_schema() {
  // @@protoc_insertion_point(field_unsafe_arena_release:google.cloud.bigquery.storage.v1.ReadSession.arrow_schema)
  if (_internal_has_arrow_schema()) {
    clear_has_schema();
    ::google::cloud::bigquery::storage::v1::ArrowSchema* temp = schema_.arrow_schema_;
    schema_.arrow_schema_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ReadSession::unsafe_arena_set_allocated_arrow_schema(::google::cloud::bigquery::storage::v1::ArrowSchema* arrow_schema) {
  clear_schema();
  if (arrow_schema) {
    set_has_arrow_schema();
    schema_.arrow_schema_ = arrow_schema;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:google.cloud.bigquery.storage.v1.ReadSession.arrow_schema)
}
inline ::google::cloud::bigquery::storage::v1::ArrowSchema* ReadSession::_internal_mutable_arrow_schema() {
  if (!_internal_has_arrow_schema()) {
    clear_schema();
    set_has_arrow_schema();
    schema_.arrow_schema_ = CreateMaybeMessage< ::google::cloud::bigquery::storage::v1::ArrowSchema >(GetArena());
  }
  return schema_.arrow_schema_;
}
inline ::google::cloud::bigquery::storage::v1::ArrowSchema* ReadSession::mutable_arrow_schema() {
  // @@protoc_insertion_point(field_mutable:google.cloud.bigquery.storage.v1.ReadSession.arrow_schema)
  return _internal_mutable_arrow_schema();
}

// string table = 6 [(.google.api.field_behavior) = IMMUTABLE, (.google.api.resource_reference) = {
inline void ReadSession::clear_table() {
  table_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ReadSession::table() const {
  // @@protoc_insertion_point(field_get:google.cloud.bigquery.storage.v1.ReadSession.table)
  return _internal_table();
}
inline void ReadSession::set_table(const std::string& value) {
  _internal_set_table(value);
  // @@protoc_insertion_point(field_set:google.cloud.bigquery.storage.v1.ReadSession.table)
}
inline std::string* ReadSession::mutable_table() {
  // @@protoc_insertion_point(field_mutable:google.cloud.bigquery.storage.v1.ReadSession.table)
  return _internal_mutable_table();
}
inline const std::string& ReadSession::_internal_table() const {
  return table_.Get();
}
inline void ReadSession::_internal_set_table(const std::string& value) {
  
  table_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ReadSession::set_table(std::string&& value) {
  
  table_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:google.cloud.bigquery.storage.v1.ReadSession.table)
}
inline void ReadSession::set_table(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  table_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:google.cloud.bigquery.storage.v1.ReadSession.table)
}
inline void ReadSession::set_table(const char* value,
    size_t size) {
  
  table_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:google.cloud.bigquery.storage.v1.ReadSession.table)
}
inline std::string* ReadSession::_internal_mutable_table() {
  
  return table_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ReadSession::release_table() {
  // @@protoc_insertion_point(field_release:google.cloud.bigquery.storage.v1.ReadSession.table)
  return table_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ReadSession::set_allocated_table(std::string* table) {
  if (table != nullptr) {
    
  } else {
    
  }
  table_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), table,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:google.cloud.bigquery.storage.v1.ReadSession.table)
}

// .google.cloud.bigquery.storage.v1.ReadSession.TableModifiers table_modifiers = 7 [(.google.api.field_behavior) = OPTIONAL];
inline bool ReadSession::_internal_has_table_modifiers() const {
  return this != internal_default_instance() && table_modifiers_ != nullptr;
}
inline bool ReadSession::has_table_modifiers() const {
  return _internal_has_table_modifiers();
}
inline void ReadSession::clear_table_modifiers() {
  if (GetArena() == nullptr && table_modifiers_ != nullptr) {
    delete table_modifiers_;
  }
  table_modifiers_ = nullptr;
}
inline const ::google::cloud::bigquery::storage::v1::ReadSession_TableModifiers& ReadSession::_internal_table_modifiers() const {
  const ::google::cloud::bigquery::storage::v1::ReadSession_TableModifiers* p = table_modifiers_;
  return p != nullptr ? *p : *reinterpret_cast<const ::google::cloud::bigquery::storage::v1::ReadSession_TableModifiers*>(
      &::google::cloud::bigquery::storage::v1::_ReadSession_TableModifiers_default_instance_);
}
inline const ::google::cloud::bigquery::storage::v1::ReadSession_TableModifiers& ReadSession::table_modifiers() const {
  // @@protoc_insertion_point(field_get:google.cloud.bigquery.storage.v1.ReadSession.table_modifiers)
  return _internal_table_modifiers();
}
inline void ReadSession::unsafe_arena_set_allocated_table_modifiers(
    ::google::cloud::bigquery::storage::v1::ReadSession_TableModifiers* table_modifiers) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(table_modifiers_);
  }
  table_modifiers_ = table_modifiers;
  if (table_modifiers) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:google.cloud.bigquery.storage.v1.ReadSession.table_modifiers)
}
inline ::google::cloud::bigquery::storage::v1::ReadSession_TableModifiers* ReadSession::release_table_modifiers() {
  
  ::google::cloud::bigquery::storage::v1::ReadSession_TableModifiers* temp = table_modifiers_;
  table_modifiers_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::google::cloud::bigquery::storage::v1::ReadSession_TableModifiers* ReadSession::unsafe_arena_release_table_modifiers() {
  // @@protoc_insertion_point(field_release:google.cloud.bigquery.storage.v1.ReadSession.table_modifiers)
  
  ::google::cloud::bigquery::storage::v1::ReadSession_TableModifiers* temp = table_modifiers_;
  table_modifiers_ = nullptr;
  return temp;
}
inline ::google::cloud::bigquery::storage::v1::ReadSession_TableModifiers* ReadSession::_internal_mutable_table_modifiers() {
  
  if (table_modifiers_ == nullptr) {
    auto* p = CreateMaybeMessage<::google::cloud::bigquery::storage::v1::ReadSession_TableModifiers>(GetArena());
    table_modifiers_ = p;
  }
  return table_modifiers_;
}
inline ::google::cloud::bigquery::storage::v1::ReadSession_TableModifiers* ReadSession::mutable_table_modifiers() {
  // @@protoc_insertion_point(field_mutable:google.cloud.bigquery.storage.v1.ReadSession.table_modifiers)
  return _internal_mutable_table_modifiers();
}
inline void ReadSession::set_allocated_table_modifiers(::google::cloud::bigquery::storage::v1::ReadSession_TableModifiers* table_modifiers) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete table_modifiers_;
  }
  if (table_modifiers) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(table_modifiers);
    if (message_arena != submessage_arena) {
      table_modifiers = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, table_modifiers, submessage_arena);
    }
    
  } else {
    
  }
  table_modifiers_ = table_modifiers;
  // @@protoc_insertion_point(field_set_allocated:google.cloud.bigquery.storage.v1.ReadSession.table_modifiers)
}

// .google.cloud.bigquery.storage.v1.ReadSession.TableReadOptions read_options = 8 [(.google.api.field_behavior) = OPTIONAL];
inline bool ReadSession::_internal_has_read_options() const {
  return this != internal_default_instance() && read_options_ != nullptr;
}
inline bool ReadSession::has_read_options() const {
  return _internal_has_read_options();
}
inline void ReadSession::clear_read_options() {
  if (GetArena() == nullptr && read_options_ != nullptr) {
    delete read_options_;
  }
  read_options_ = nullptr;
}
inline const ::google::cloud::bigquery::storage::v1::ReadSession_TableReadOptions& ReadSession::_internal_read_options() const {
  const ::google::cloud::bigquery::storage::v1::ReadSession_TableReadOptions* p = read_options_;
  return p != nullptr ? *p : *reinterpret_cast<const ::google::cloud::bigquery::storage::v1::ReadSession_TableReadOptions*>(
      &::google::cloud::bigquery::storage::v1::_ReadSession_TableReadOptions_default_instance_);
}
inline const ::google::cloud::bigquery::storage::v1::ReadSession_TableReadOptions& ReadSession::read_options() const {
  // @@protoc_insertion_point(field_get:google.cloud.bigquery.storage.v1.ReadSession.read_options)
  return _internal_read_options();
}
inline void ReadSession::unsafe_arena_set_allocated_read_options(
    ::google::cloud::bigquery::storage::v1::ReadSession_TableReadOptions* read_options) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(read_options_);
  }
  read_options_ = read_options;
  if (read_options) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:google.cloud.bigquery.storage.v1.ReadSession.read_options)
}
inline ::google::cloud::bigquery::storage::v1::ReadSession_TableReadOptions* ReadSession::release_read_options() {
  
  ::google::cloud::bigquery::storage::v1::ReadSession_TableReadOptions* temp = read_options_;
  read_options_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::google::cloud::bigquery::storage::v1::ReadSession_TableReadOptions* ReadSession::unsafe_arena_release_read_options() {
  // @@protoc_insertion_point(field_release:google.cloud.bigquery.storage.v1.ReadSession.read_options)
  
  ::google::cloud::bigquery::storage::v1::ReadSession_TableReadOptions* temp = read_options_;
  read_options_ = nullptr;
  return temp;
}
inline ::google::cloud::bigquery::storage::v1::ReadSession_TableReadOptions* ReadSession::_internal_mutable_read_options() {
  
  if (read_options_ == nullptr) {
    auto* p = CreateMaybeMessage<::google::cloud::bigquery::storage::v1::ReadSession_TableReadOptions>(GetArena());
    read_options_ = p;
  }
  return read_options_;
}
inline ::google::cloud::bigquery::storage::v1::ReadSession_TableReadOptions* ReadSession::mutable_read_options() {
  // @@protoc_insertion_point(field_mutable:google.cloud.bigquery.storage.v1.ReadSession.read_options)
  return _internal_mutable_read_options();
}
inline void ReadSession::set_allocated_read_options(::google::cloud::bigquery::storage::v1::ReadSession_TableReadOptions* read_options) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete read_options_;
  }
  if (read_options) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(read_options);
    if (message_arena != submessage_arena) {
      read_options = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, read_options, submessage_arena);
    }
    
  } else {
    
  }
  read_options_ = read_options;
  // @@protoc_insertion_point(field_set_allocated:google.cloud.bigquery.storage.v1.ReadSession.read_options)
}

// repeated .google.cloud.bigquery.storage.v1.ReadStream streams = 10 [(.google.api.field_behavior) = OUTPUT_ONLY];
inline int ReadSession::_internal_streams_size() const {
  return streams_.size();
}
inline int ReadSession::streams_size() const {
  return _internal_streams_size();
}
inline void ReadSession::clear_streams() {
  streams_.Clear();
}
inline ::google::cloud::bigquery::storage::v1::ReadStream* ReadSession::mutable_streams(int index) {
  // @@protoc_insertion_point(field_mutable:google.cloud.bigquery.storage.v1.ReadSession.streams)
  return streams_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::google::cloud::bigquery::storage::v1::ReadStream >*
ReadSession::mutable_streams() {
  // @@protoc_insertion_point(field_mutable_list:google.cloud.bigquery.storage.v1.ReadSession.streams)
  return &streams_;
}
inline const ::google::cloud::bigquery::storage::v1::ReadStream& ReadSession::_internal_streams(int index) const {
  return streams_.Get(index);
}
inline const ::google::cloud::bigquery::storage::v1::ReadStream& ReadSession::streams(int index) const {
  // @@protoc_insertion_point(field_get:google.cloud.bigquery.storage.v1.ReadSession.streams)
  return _internal_streams(index);
}
inline ::google::cloud::bigquery::storage::v1::ReadStream* ReadSession::_internal_add_streams() {
  return streams_.Add();
}
inline ::google::cloud::bigquery::storage::v1::ReadStream* ReadSession::add_streams() {
  // @@protoc_insertion_point(field_add:google.cloud.bigquery.storage.v1.ReadSession.streams)
  return _internal_add_streams();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::google::cloud::bigquery::storage::v1::ReadStream >&
ReadSession::streams() const {
  // @@protoc_insertion_point(field_list:google.cloud.bigquery.storage.v1.ReadSession.streams)
  return streams_;
}

inline bool ReadSession::has_schema() const {
  return schema_case() != SCHEMA_NOT_SET;
}
inline void ReadSession::clear_has_schema() {
  _oneof_case_[0] = SCHEMA_NOT_SET;
}
inline ReadSession::SchemaCase ReadSession::schema_case() const {
  return ReadSession::SchemaCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// ReadStream

// string name = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];
inline void ReadStream::clear_name() {
  name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ReadStream::name() const {
  // @@protoc_insertion_point(field_get:google.cloud.bigquery.storage.v1.ReadStream.name)
  return _internal_name();
}
inline void ReadStream::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:google.cloud.bigquery.storage.v1.ReadStream.name)
}
inline std::string* ReadStream::mutable_name() {
  // @@protoc_insertion_point(field_mutable:google.cloud.bigquery.storage.v1.ReadStream.name)
  return _internal_mutable_name();
}
inline const std::string& ReadStream::_internal_name() const {
  return name_.Get();
}
inline void ReadStream::_internal_set_name(const std::string& value) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ReadStream::set_name(std::string&& value) {
  
  name_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:google.cloud.bigquery.storage.v1.ReadStream.name)
}
inline void ReadStream::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:google.cloud.bigquery.storage.v1.ReadStream.name)
}
inline void ReadStream::set_name(const char* value,
    size_t size) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:google.cloud.bigquery.storage.v1.ReadStream.name)
}
inline std::string* ReadStream::_internal_mutable_name() {
  
  return name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ReadStream::release_name() {
  // @@protoc_insertion_point(field_release:google.cloud.bigquery.storage.v1.ReadStream.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ReadStream::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:google.cloud.bigquery.storage.v1.ReadStream.name)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace storage
}  // namespace bigquery
}  // namespace cloud
}  // namespace google

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::google::cloud::bigquery::storage::v1::DataFormat> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::google::cloud::bigquery::storage::v1::DataFormat>() {
  return ::google::cloud::bigquery::storage::v1::DataFormat_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_google_2fcloud_2fbigquery_2fstorage_2fv1_2fstream_2eproto
