# Generated by cpp11: do not edit by hand

bqs_init_logger <- function() {
  invisible(.Call("_bigrquerystorage_bqs_init_logger", PACKAGE = "bigrquerystorage"))
}

bqs_set_log_verbosity <- function(verbose) {
  invisible(.Call("_bigrquerystorage_bqs_set_log_verbosity", verbose, PACKAGE = "bigrquerystorage"))
}

grpc_version <- function() {
  .Call("_bigrquerystorage_grpc_version", PACKAGE = "bigrquerystorage")
}

bqs_ipc_stream <- function(project, dataset, table, parent, client_info, service_configuration, access_token, timestamp_seconds, timestamp_nanos, selected_fields, row_restriction) {
  .Call("_bigrquerystorage_bqs_ipc_stream", project, dataset, table, parent, client_info, service_configuration, access_token, timestamp_seconds, timestamp_nanos, selected_fields, row_restriction, PACKAGE = "bigrquerystorage")
}
