# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bqs_set_log_verbosity <- function(severity) {
    invisible(.Call('_bigrquerystorage_bqs_set_log_verbosity', PACKAGE = 'bigrquerystorage', severity))
}

bqs_init_logger <- function() {
    invisible(.Call('_bigrquerystorage_bqs_init_logger', PACKAGE = 'bigrquerystorage'))
}

grpc_version <- function() {
    .Call('_bigrquerystorage_grpc_version', PACKAGE = 'bigrquerystorage')
}

#' @noRd
bqs_ipc_stream <- function(project, dataset, table, parent, n, client_info, service_configuration, access_token, root_certificate, timestamp_seconds, timestamp_nanos, selected_fields, row_restriction, quiet = FALSE) {
    .Call('_bigrquerystorage_bqs_ipc_stream', PACKAGE = 'bigrquerystorage', project, dataset, table, parent, n, client_info, service_configuration, access_token, root_certificate, timestamp_seconds, timestamp_nanos, selected_fields, row_restriction, quiet)
}

