# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Check grpc version
#' @return Version string and what g stands for
#' @export
grpc_version <- function() {
    .Call('_bigrquerystorage_grpc_version', PACKAGE = 'bigrquerystorage')
}

