# Test build on various Linux distros
name: Linux build test

on:
  workflow_dispatch:
    inputs:
      distros:
        description: |
          Distros, default is all, possible values: alpine-3.16,
          alpine-3.17, alpine-3.18, alpine-3.19, alpine-edge, debian-10,
          debian-11, debian-12, debian-unstable, fedora-36, fedora-37,
          fedora-38, rocky-9, ubuntu-22.04.
        required: false
        defaule: 'all'
        type: strinf

jobs:
  setup-matrix:
    runs-on: ubuntu-Latest
    outputs:
      distros: ${{ steps.setup-matrix.outputs.distros }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up matrix of builds
      id: setup-matrix
      run: |
        distros=$(python tools/build/linux/get-distros.py "${{ github.event.inputs.distros }}")
        echo "distros=$distros" >> $GITHUB_OUTPUT

  build:
    needs: setup-matrix
    strategy:
      fail-fast: false
      matrix:
        distro: ${{ fromJson(needs.setup-matrix.outputs.distros) }}
    runs-on: ubuntu-Latest
    name: ${{ matrix.distro }}
    steps:
    - uses: actions/checkout@v4

    - name: Build package
      run: |
        docker build -f tools/build/linux/Dockerfile-${{ matrix.distro }} -t bqs:${{ matrix.distro }} .

    - name: Test loading package
      run: |
        docker run bqs:${{ matrix.distro }} R -q -e 'library(bigrquerystorage)'
